yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('/create/', views.post_create, name='post_create'),
    path('profile/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls', namespace='auth')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {'text', 'group'}

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .models import Post, Group
from .forms import PostForm


def index(request):
    post_list = Post.objects.select_related(
        'group',
        'author'
    )
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username: str):
    posts = Post.objects.select_related(
        'group',
    ).filter(author__username=username)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'username': username,
        'page_obj': page_obj,
        'posts_count': posts.count(),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    author_posts_count = post.author.posts.count()
    context = {
        'post': post,
        'author_posts_count': author_posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    group_list = Group.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect(
                reverse_lazy(
                    'posts:profile',
                    kwargs={'username': request.user.username},
                )
            )
        context = {
            'form': form,
            'group_list': group_list,
            'is_edit': False,
        }
        return render(request, 'posts/create_post.html', context)
    form = PostForm()
    context = {
        'form': form,
        'group_list': group_list,
        'is_edit': False,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    edited_post = get_object_or_404(Post, id=post_id)
    group_list = Group.objects.all()
    if request.user == edited_post.author:
        if request.method == 'POST':
            form = PostForm(request.POST or None, instance=edited_post)
            context = {
                'form': form,
                'group_list': group_list,
                'is_edit': True,
            }
            if form.is_valid():
                form.save()
                return redirect(
                    reverse_lazy(
                        'posts:profile',
                        kwargs={'username': request.user.username}
                    )
                )
            return render(request, 'posts/create_post.html', context)
        form = PostForm(request.POST or None, instance=edited_post)
        context = {
            'form': form,
            'group_list': group_list,
            'is_edit': True,
        }
        return render(request, 'posts/create_post.html', context)
    return redirect(
        reverse_lazy(
            'posts:post_detail',
            kwargs={'post_id': post_id}
        )
    )

yatube/templates/posts/create_post.html
<!DOCTYPE html>
{% extends 'base.html' %}

<html lang="ru"> 
  {% block title %}Новый пост{% endblock %}
  <body>	   
    <main>
      {% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit is True %}
                Редактировать запись
                {% else %}
                Добавить запись         
                {% endif %}    
              </div>
              <div class="card-body">        
                {% if is_edit is True %}
                <form method="post" action="{% url 'posts:post_edit' form.instance.id %}">
                {% else %}
                <form method="post" action="{% url 'posts:post_create' %}">
                {% endif %}
                  {% csrf_token %}         
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста             
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                     {% if is_edit is True %}
                     Текст редактируемого поста
                     {% else %}
                     Текст нового поста
                     {% endif %}
                    </small>                  
                  </div>    
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      {% for group in group_list %}
                      <option value="{{ group.id }}">{{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit is True %}
                      Редактировать
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% endblock %}
    </main>
  </body>
</html>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Последние посты группы {{ posts.group }}
{% endblock %}
{% block content %}
  <h1>Последние посты группы {{ posts.group }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние изменения на сайте
{% endblock %}
{% block content %}
  <h1>Главная страница</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}  

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

<html lang="ru">
  {% block title %}
    Пост {{ post.text|truncatechars:30 }}
  {% endblock %}
  <body>
    <main>
      {% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date }} 
            </li>
            {% if post.group %} 
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.first_name }} {{post.author.last_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ author_posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>{{ post.text }}</p>
        </article>
      </div> 
    {% endblock %}  
    </main>
  </body>
</html>

yatube/templates/posts/profile.html
{% extends 'base.html' %}

<html lang="ru">
    {% block title %}{{ username }}{% endblock %}
  <body>       
    <main>
      {% block content %}     
        <h1>Все посты пользователя {{ username }} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>
        {% for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{ post.author }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date }} 
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article> 
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}          
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}  
      {% endblock %}
    </main>
  </body>
</html>